import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#252a34',
  '--slot4-page-text': '#eaeaea',
  '--slot4-panel-bg': '#2d3340',
  '--slot4-surface-bg': '#fbfaf7',
  '--slot4-muted-text': '#aeb5c0',
  '--slot4-soft-muted-text': '#73808f',
  '--slot4-accent': '#08d9d6',
  '--slot4-accent-fill': '#ff2e63',
  '--slot4-accent-soft': 'rgba(8, 217, 214, 0.14)',
  '--slot4-on-accent': '#0f1218',
  '--slot4-dark-bg': '#1d222c',
  '--slot4-dark-text': '#f7f5f2',
  '--slot4-media-bg': '#313845',
  '--slot4-cream': '#f4f1ea',
  '--slot4-warm': '#ece7dc',
  '--slot4-lavender': '#312936',
  '--slot4-gray': '#cfd4dc',
  '--slot4-body-gradient': 'radial-gradient(circle at top, rgba(255,46,99,0.18), transparent 26%), linear-gradient(180deg, #252a34 0%, #20242d 100%)',
  '--editable-page-bg': '#252a34',
  '--editable-page-text': '#eaeaea',
  '--editable-container': '1500px',
  '--editable-border': 'rgba(234, 234, 234, 0.12)',
  '--editable-nav-bg': 'rgba(37, 42, 52, 0.82)',
  '--editable-nav-text': '#f7f5f2',
  '--editable-nav-active': '#08d9d6',
  '--editable-nav-active-text': '#0f1218',
  '--editable-cta-bg': '#ffc21c',
  '--editable-cta-text': '#1d222c',
  '--editable-search-bg': '#fbfaf7',
  '--editable-footer-bg': '#211d28',
  '--editable-footer-text': '#f7f5f2',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_18px_40px_rgba(8,15,25,0.18)]',
  shadowStrong: 'shadow-[0_28px_80px_rgba(6,10,18,0.34)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(13,16,22,0.08),rgba(13,16,22,0.78))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8',
    sectionY: 'py-14 sm:py-16 lg:py-20',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[140px] shrink-0 snap-start sm:w-[160px]',
  },
  type: {
    eyebrow: 'text-xs font-semibold uppercase tracking-[0.28em] text-[var(--slot4-accent)]',
    heroTitle: 'text-4xl font-semibold leading-[0.96] tracking-[-0.06em] sm:text-6xl lg:text-[4.5rem]',
    sectionTitle: 'text-3xl font-semibold tracking-[-0.05em] sm:text-5xl',
    body: 'text-base leading-relaxed',
  },
  surface: {
    card: `rounded-[2rem] border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-[2rem] border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-[2rem] ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--editable-cta-bg)] px-7 py-3 text-sm font-bold tracking-[0.01em] text-[var(--editable-cta-text)] transition duration-300 hover:-translate-y-0.5 hover:brightness-95 active:scale-[0.98]`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-full border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-6 py-3 text-sm font-bold tracking-[0.01em] text-[#1f2430] transition duration-300 hover:border-[var(--slot4-accent)] hover:text-[var(--slot4-accent)] active:scale-[0.98]`,
    accent: `inline-flex items-center justify-center gap-2 rounded-full ${editablePalette.accentBg} px-6 py-3 text-sm font-bold text-white transition duration-300 hover:-translate-y-0.5 hover:brightness-95 active:scale-[0.98]`,
  },
  media: {
    frame: `relative overflow-hidden rounded-[1.75rem] ${editablePalette.mediaBg}`,
    ratio: 'aspect-[2/3]',
  },
  motion: {
    lift: 'transition duration-500 hover:-translate-y-1.5 hover:shadow-[0_24px_60px_rgba(6,10,18,0.24)]',
    fade: 'transition duration-300 hover:opacity-80',
  },
} as const

export const aiLayoutRules = [
  'Change the full site color palette in editableRootStyle first; all homepage sections consume those CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use wide readable grids; never create skinny columns for paragraphs or cards.',
  'Use horizontal rails for dense post browsing, like the MysteryCoder reference layout.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
